name: Actualizar Datos de SharePoint

on:
  schedule:
    - cron: '0 13 * * 1-6' # Se ejecuta a las 8 AM COL, de Lunes a Sábado
  workflow_dispatch:      # Permite ejecutarlo manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar librerías
      run: pip install -r requirements.txt

    - name: Ejecutar script de procesamiento
      run: python main.py # Asegúrate que tu código se llame main.py

    - name: Guardar cambios en GitHub
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add data_procesada.csv
        git commit -m "Actualización automática: Símbolos ✓ y X aplicados" || exit 0
        git push
