name: Actualizar Reporte Manpower

on:
  schedule:
    - cron: '0 13 * * 1-6' # 8 AM COL, Lunes a Sábado
  workflow_dispatch:      # Botón manual para pruebas

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Permisos necesarios para subir el HTML generado
    permissions:
      contents: write
      
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          pip install pandas requests openpyxl

      - name: Ejecutar script unificado
        # Aquí es donde le decimos que use index.py en lugar de main.py
        run: python index.py

      - name: Guardar y subir cambios
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          # Esto añade el index.html que genera tu script
          git add .
          git commit -m "Reporte actualizado automáticamente" || exit 0
          git push
