name: Actualizar Reporte Manpower

on:
  schedule:
    - cron: '0 13 * * 1-6' # 8 AM COL, Lunes a Sábado
  workflow_dispatch:      # Botón manual

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Esto ayuda a evitar el error 403
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          pip install pandas requests openpyxl

      - name: Ejecutar script de procesamiento
        run: python main.py

      - name: Guardar y subir cambios
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          # El '|| exit 0' evita que el workflow falle si no hay datos nuevos
          git commit -m "Reporte actualizado automáticamente" || exit 0
          git push
