name: Actualizar Reporte Manpower

on:
  schedule:
    - cron: '0 13 * * 1-6' # 8 AM COL
  workflow_dispatch:      # Botón manual

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # IMPORTANTE: Evita el error 403
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install pandas requests openpyxl

      - name: Ejecutar script
        run: python index.py

      - name: Guardar cambios
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          # git add . en lugar de index.html para que encuentre el archivo nuevo
          git add . 
          git commit -m "Actualización automática de reporte" || exit 0
          git push
